### ISSUE TITLE
Hey 

### ISSUE THREAD

**Issue by jConsull** [victti/BSGO-Server-Emulator#2]
When is the release date? ♥

**Comment by victti** [comment]
I work on this on my free time and I don't give as much attention as I used to, so maybe it will never be ready for a release. I recommend you checking out other players private servers if you are interesting on playing the game, there are at least two on going projects atm afaik

**Comment by Nepmia** [comment]
One of them has potential but the people behind it have a "it was better before" mindset and removed a lot of the new content from the lastest version of the game (aka carriers and stealth + a lot of stuff for roles) which is okay but not the best especially if you want the og vibe,

second project is the closest i've seen to the og game BUT it has ofc a downside or i wouldn't be wirtting here, the dev behind it abuse his powers all the time and plays with maxed stuff (so he can really see what average player experience is lol) in teamfights.. his looting system is not scallable (what a genius idea for a MMO) so you never get anything, only reliable way of farming in this project is to afk farm plats ... yep sounds like something super cool to do right ?

so yep there are "playable" project but it's not personally the fun i'm searching, i hope you are still working on your OS version cause that would be sick and imo if you don't have time to polish you should still release what you've done, another good side of open source is that other people can help you improve stuff
